config/routes.rb
Rails.application.routes.draw do


  namespace :public do
    get 'customers/show'
    get 'customers/edit'
  end
  namespace :public do
    get 'homes/top'
    get 'homes/about'
  end
   namespace :public do
    get 'addresses/index'
    get 'addresses/edit'
  end
  devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  namespace :admin do
    resources :genres,only: [:index,:create,:edit,:update]
    resources :items,only: [:index,:new,:create,:show,:edit,:update]
    resources :customers,only: [:index,:show,:edit,:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
   has_one_attached :image
   belongs_to :genre
   def status_text
     if is_active == true
       "販売中"
     else
       "販売停止中"
     end
   end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
def new
  @item = Item.new
end
def create
  @item = Item.new(item_params)
  @item.save
  redirect_to admin_items_path
end
def index
  @items = Item.all
end

def show
  @item = Item.find(params[:id])
end
def edit
    @item = Item.find(params[:id])
end

def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item)
end
private
def item_params
  params.require(:item).permit(:name,:introduction,:genre_id,:price,:is_active)
end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<h1>商品編集</h1>
<%= form_with model: @item, url: admin_item_path(@item) do |f| %>

    <div class="form-group has-icon">
      <%= f.label :image %><br />
      <%= f.file_field :image %>

    </div>
    <div class="form-group has-icon">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="form-group has-icon">
      <%= f.label :genre_id, "ジャンル名" %>
      <%= f.collection_select :genre_id, Genre.all, :id, :name %>

    </div>
    <div class="form-group has-icon">
      <%= f.label :price %>
      <%= f.text_field :price %>

    </div>
    <div class="form-group has-icon">
      <%= f.radio_button :is_active, :on_sale %>
  　  　 <%= f.label :is_active,"販売中", {value: :true, style: "display: inline-block;"} %>
  　　 <%= f.radio_button :is_active, :off_sale %>
  　　 <%= f.label :is_active, "販売停止中", {value: :false, style: "display: inline-block;"} %>

    </div>
    <%= f.submit "変更を保存", class:"btn btn-primary btn-block btn-base-1 mt-20" %>
  <% end %>

app/views/admin/items/index.html.erb
<h1>商品一覧</h1>
<table>
<tr>
  <th>商品ID</th>
  <th>商品名</th>
  <th>商品単価</th>
  <th>ジャンル</th>
  <th>販売ステータス</th>
</tr>
<% @items.each do |item| %>
  <tr>
    <td><%= item.id %></td>
    <td><%= link_to item.name, admin_item_path(item.id) %></td>
    <td><%= item.price %></td>
    <td><%= item.genre.name %></td>
    <td><%= item.status_text %></td>
  </tr>
<% end %>

app/views/admin/items/new.html.erb
<h1>商品 新規登録画面</h1>
<%= form_with model: @item, url: admin_items_path do |f| %>
<%=  f.file_field :image, accept: "image/*"  %>
      <h3>商品名          <%= f.text_field :name %></h3>
      <h3>商品説明        <%= f.text_area :introduction %></h3>
      <h3>ジャンル        <%= f.collection_select :genre_id, Genre.all, :id, :name %></h3>
      <h3>税抜価格        <%= f.number_field :price %>円</h3>
      <h3>販売ステータス   <%= f.radio_button :is_active, :on_sale, checked: "checked"%>
       <%= f.label :is_active, "販売中", {value: :"0", style: "display: inline-block;"} %>
       <%= f.radio_button :is_active, :off_sale %>
       <%= f.label :is_active, "販売停止中", {value: :"1", style: "display: inline-block;"} %></h3>
      <%= f.submit '新規登録', class: "btn btn-primary" %>
<% end %>

app/views/admin/items/show.html.erb
<h2>商品詳細</h2>
<% if @item.image.attached? %>
    <%= image_tag item.image, size: "200x200" %>
  <% else %>
    <%= image_tag 'no_image', size: "200x200" %>
  <% end %>
  <table class="table">
    <tr>
        <th>商品名</th>
        <td><%= @item.name%></td>
    </tr>
    <tr>
        <th>商品説明</th>
        <td><%= @item.introduction %></td>
    </tr>
    <tr>
        <th>ジャンル</th>
        <td><%= @item.genre.name %></td>
    </tr>
    <tr>
        <th>税抜き価格</th>
        <td><%= @item.price %></td>
    </tr>

    <tr>
        <th>販売ステータス</th>
        <td><%= @item.status_text %></td>
    </tr>
    </table>
    <%= link_to "編集する", edit_admin_item_path(@item) %>