config/routes.rb
Rails.application.routes.draw do


  namespace :public do
    get 'customers/show'
    get 'customers/edit'
  end
  namespace :public do
    get 'homes/top'
    get 'homes/about'
  end
   namespace :public do
    get 'addresses/index'
    get 'addresses/edit'
  end
  devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  namespace :admin do
    resources :genres,only: [:index,:create,:edit,:update]
    resources :items,only: [:index,:new,:create,:show,:edit,:update]
    resources :customers,only: [:index,:show,:edit,:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   def full_name
    first_name + last_name
   end
   def status_text
     if is_active == true
       "有効"
     else
       "無効"
     end
   end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customer_path(customer)
  end

  private
  def customer_params
     params.require(:customer).permit(:full_name,:full_name_kana,:email,:postal_code,:address,:telephone_number,:is_active)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/edit.html.erb
<h1><%= customer.first_name %>さんの会員情報編集</h1>
<%= form_with model: @customer, url: admin_customer_path(@customer) do |f| %>

    <div class="form-group has-icon">
      <%= f.label :id, "会員ID" %><br />
      <%= f.id %>

    </div>
    <div class="form-group has-icon">
      <%= f.label :full_name, "氏名" %>
      <%= f.text_field :full_name %>
    </div>
    <div class="form-group has-icon">
      <%= f.label :full_name_kana, "フリガナ" %>
      <%= f.text_field :fullname_kana %>

    </div>
    <div class="form-group has-icon">
      <%= f.label :postal_code, "郵便番号" %>
      <%= f.text_field :postal_code %>

    </div>
    <div class="form-group has-icon">
      <%= f.label :address, "住所" %>
      <%= f.text_field :address %>

    </div>
    <div class="form-group has-icon">
      <%= f.label :telephone_number, "電話番号" %>
      <%= f.text_field :telephone_number %>

    </div>
    <div class="form-group has-icon">
      <%= f.radio_button :is_active, :on_sale %>
  　  　 <%= f.label :is_active,"有効", {value: :true, style: "display: inline-block;"} %>
  　　 <%= f.radio_button :is_active, :off_sale %>
  　　 <%= f.label :is_active, "無効", {value: :false, style: "display: inline-block;"} %>

    </div>
    <%= f.submit "変更を保存", class:"btn btn-primary btn-block btn-base-1 mt-20" %>
  <% end %>

app/views/admin/customers/index.html.erb
<h1>会員一覧</h1>
<table>
<tr>
  <th>会員ID</th>
  <th>氏名</th>
  <th>アドレス</th>
  <th>販売ステータス</th>
</tr>
<% @customers.each do |customer| %>
  <tr>
    <td><%= customer.id %></td>
    <td><%= customer.full_name %></td>
    <td><%= customer.email %></td>
    <td><%= customer.status_text %></td>
  </tr>
<% end %>

app/views/admin/customers/show.html.erb
<h2><%= customer.last_name %>さんの会員詳細</h2>

  <table class="table">
    <tr>
        <th>会員ID</th>
        <td><%= @customer.id%></td>
    </tr>
    <tr>
        <th>氏名</th>
        <td><%= @customer.full_name%></td>
    </tr>
    <tr>
        <th>フリガナ</th>
        <td><%= @customer.full_name_kana %></td>
    </tr>
    <tr>
        <th>郵便番号</th>
        <td><%= @customer.postal_code %></td>
    </tr>
    <tr>
        <th>住所</th>
        <td><%= @customer.address %></td>
    </tr>
    <tr>
        <th>電話番号</th>
        <td><%= @customer.telephone_number %></td>
    </tr>
    <tr>
        <th>アドレス</th>
        <td><%= @customer.email %></td>
    </tr>
    <tr>
        <th>販売ステータス</th>
        <td><%= @customer.status_text %></td>
    </tr>
    </table>
    <%= link_to "編集する", edit_admin_customer_path(@customer) %>