config/routes.rb
Rails.application.routes.draw do


  namespace :public do
    get 'customers/show'
    get 'customers/edit'
  end
  namespace :public do
    get 'homes/top'
    get 'homes/about'
  end
   namespace :public do
    get 'addresses/index'
    get 'addresses/edit'
  end
  devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  namespace :admin do
    resources :genres,only: [:index,:create,:edit,:update]
    resources :items,only: [:index,:new,:create,:show,:edit,:update]
    resources :customers,only: [:index,:show,:edit,:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end
  def edit
    @genre = Genre.find(params[:id])
  end
  def update
    genre = Genre.find(params[:id])
    Genre.update(genre_params)
    redirect_to admin_genre_path(genre.id)
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<h1>ジャンル編集</h1>

<%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>

  <h4>ジャンル名</h4>
  <%= f.text_field :name %>

  <%= f.submit '変更を保存' %>

<% end %>

app/views/admin/genres/index.html.erb
<h1>ジャンル一覧・追加</h1>

<%= form_with model: @genre, url: admin_genres_path do |f| %>
<h3>
<%= f.label :ジャンル%><br>
<%= f.text_field :name %>
 <%= f.submit '新規登録' %>
 <% end %>
</h3>
 <h2>ジャンル</h2>
      <table class="table">
       <thead>
        <tr>
         <th></th>
         <th></th>

        </tr>
      </thead>
      <tbody>
        <% @genres.each do |genre| %>
        <tr>
          <td><%= genre.name %></td>
          <td><%= link_to "編集する", edit_admin_genre_path(genre.id) %></td>
        </tr>
        <% end %>
      </tbody>